name: Playwright Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'
  push:
    branches:
      - main
jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Set up Docker
        run: |
          docker pull mcr.microsoft.com/playwright:v1.49.0-jammy # Pull the Playwright Docker image
          docker run --rm mcr.microsoft.com/playwright:v1.49.0-jammy npx playwright install --with-deps

      - name: Run Playwright tests in Docker
        env:
          EMAIL: nadya0704@gmail.com
          PASSWORD: e3#6heR$Aq$LG.d
        run: |
          docker run -v ${{ github.workspace }}:/app -w /app --rm \
          -e EMAIL=nadya0704@gmail.com \
          -e PASSWORD=e3#6heR$Aq$LG.d \
          mcr.microsoft.com/playwright:v1.49.0-jammy \
          npx playwright test --reporter=list
          
           # Step 6: Upload Playwright report
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
