name: Playwright Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'
  push:
    branches:
      - main

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        run: docker pull mcr.microsoft.com/playwright:v1.49.0-jammy

      - name: Run Playwright tests in Docker
        env:
          EMAIL: nadya0704@gmail.com
          PASSWORD: e3#6heR$Aq$LG.d
        run: |
          mkdir -p playwright-report
          docker run -v ${{ github.workspace }}:/app -w /app --rm \
          -e EMAIL=nadya0704@gmail.com \
          -e PASSWORD=e3#6heR$Aq$LG.d \
          mcr.microsoft.com/playwright:v1.49.0-jammy \
          npx playwright test --reporter=html --output=playwright-report || true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30